//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sparrow.Services.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPRW_MARKET_STATES
    {
        public SPRW_MARKET_STATES()
        {
            this.SPRW_MARKET_LOCATIONS = new HashSet<SPRW_MARKET_LOCATIONS>();
        }
    
        public int STATE_ID { get; set; }
        public string STATE_NAME { get; set; }
    
        public virtual ICollection<SPRW_MARKET_LOCATIONS> SPRW_MARKET_LOCATIONS { get; set; }
    }
}
