//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sparrow.Services.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPRW_MARKET_LOCATIONS
    {
        public SPRW_MARKET_LOCATIONS()
        {
            this.SPRW_ARTIST = new HashSet<SPRW_ARTIST>();
        }
    
        public int MARKET_ID { get; set; }
        public string CITY { get; set; }
        public int STATE { get; set; }
        public decimal LAT_COORDS { get; set; }
        public decimal LONG_COORDS { get; set; }
        public int ZIP { get; set; }
    
        public virtual ICollection<SPRW_ARTIST> SPRW_ARTIST { get; set; }
        public virtual SPRW_MARKET_STATES SPRW_MARKET_STATES { get; set; }
    }
}
