//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sparrow.Services.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sprw_playlist
    {
        public sprw_playlist()
        {
            this.SPRW_PLAYLIST_PAGES = new HashSet<SPRW_PLAYLIST_PAGES>();
        }
    
        public long PLAYLIST_ID { get; set; }
        public bool IS_ACTIVE { get; set; }
        public System.DateTime CREATED { get; set; }
    
        public virtual ICollection<SPRW_PLAYLIST_PAGES> SPRW_PLAYLIST_PAGES { get; set; }
    }
}
