//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sparrow.Services.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPRW_PLAYLIST_PAGES
    {
        public long PLAYLIST_ID { get; set; }
        public int PAGE_NUM { get; set; }
        public string PLAYLIST { get; set; }
    
        public virtual sprw_playlist sprw_playlist { get; set; }
    }
}
