//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sparrow.Services.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPRW_POP_INDEX
    {
        public int Id { get; set; }
        public int TRACK_ID { get; set; }
        public decimal POP_INDEX { get; set; }
    
        public virtual SPRW_TRACK SPRW_TRACK { get; set; }
    }
}
