//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sparrow.Services.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPRW_ARTIST_SETTINGS
    {
        public int SETTING_ID { get; set; }
        public int ARTIST_ID { get; set; }
        public string SETTING { get; set; }
    
        public virtual SPRW_ARTIST SPRW_ARTIST { get; set; }
    }
}
